feat: Addresables integtration
StansAssets/com.stansassets.scene-management pull request #4
Opened 2020-08-27 18:51 UTC by PavelKlym

## Purpose of this PR
Very first iteration to integrate Addressables.

## Testing status
* No tests have been added.

2020-08-27 19:12 UTC, stan-osipov requested changes
Awesome! Some changes requested.

2020-08-27 19:12 UTC, stan-osipov commented on com.stansassets.scene-management/Runtime/Statis/AdditiveScenesLoader.cs
> +        public static void LoadAdditively(int sceneBuildIndex, Action<Scene> loadCompleted = null)
breaking chnage

2020-08-27 19:12 UTC, stan-osipov commented on com.stansassets.scene-management/Runtime/Statis/AdditiveScenesLoader.cs
> +        public static void LoadAdditively(int sceneBuildIndex, Action<Scene> loadCompleted = null)
make dummy for AsyncOperation

2020-08-27 19:12 UTC, stan-osipov commented on com.stansassets.scene-management/Runtime/Statis/AdditiveScenesLoader.cs
> +        public static void LoadAdditively(string sceneName, Action<Scene> loadCompleted = null)
same

2020-08-27 19:12 UTC, stan-osipov commented on com.stansassets.scene-management/Runtime/Statis/AdditiveScenesLoader.cs
> +#if UNITY_EDITOR
Application.isEditor

2020-08-27 19:12 UTC, stan-osipov commented on com.stansassets.scene-management/Runtime/Statis/AdditiveScenesLoader.cs
> +                UnloadAddressable(sceneName, unloadCompleted);
Make sure we do not unload from cache.

2020-08-27 19:12 UTC, stan-osipov commented on com.stansassets.scene-management/Runtime/Statis/AdditiveScenesLoader.cs
> +                UnloadAddressable(sceneName, unloadCompleted);
maybe we will need an additional method for that if we would want to unload addressable scene completely.

2020-08-27 19:12 UTC, stan-osipov commented on com.stansassets.scene-management/Runtime/Statis/AdditiveScenesLoader.cs
> +            #endif
Let's separate that into models

2020-08-27 19:12 UTC, stan-osipov commented on com.stansassets.scene-management/package.json
>    "unity": "2019.3",
"version": "0.0.10-preview",

2020-08-27 19:12 UTC, stan-osipov commented on com.stansassets.scene-management/BuildConfigurator/Editor/BuildScenesPreprocessor.cs
> +    public static class AddressablesUtility
doc is missing.

2020-08-27 19:12 UTC, stan-osipov commented on com.stansassets.scene-management/BuildConfigurator/Editor/BuildScenesPreprocessor.cs
> +        public static AddressableAssetGroup GetOrCreateGroup(string name)
doc is missing.

2020-08-27 19:12 UTC, stan-osipov commented on com.stansassets.scene-management/BuildConfigurator/Editor/Extensions/AddressableSceneAssetExtension.cs
> +    public static class AddressableSceneAssetExtension
internal

2020-08-27 19:12 UTC, stan-osipov commented on com.stansassets.scene-management/BuildConfigurator/Editor/Extensions/BuildConfigurationExtension.cs
> +    public static class BuildConfigurationExtension
internal

2020-08-27 19:12 UTC, stan-osipov commented on com.stansassets.scene-management/BuildConfigurator/Editor/Extensions/PlatformsConfigurationExtension.cs
> +    public static class PlatformsConfigurationExtension
internal

2020-08-27 19:12 UTC, stan-osipov commented on com.stansassets.scene-management/BuildConfigurator/Runtime/AddressableSceneAsset.cs
> +    public class AddressableSceneAsset
doc

2020-08-27 19:12 UTC, stan-osipov commented on com.stansassets.scene-management/BuildConfigurator/Runtime/BuildConfiguration.cs
> +    public class BuildConfiguration
doc

2020-08-27 19:12 UTC, stan-osipov commented on com.stansassets.scene-management/BuildConfigurator/Runtime/BuildConfigurationSettings.cs
>      {
doc

2020-08-27 19:12 UTC, stan-osipov commented on com.stansassets.scene-management/package.json
>    "unity": "2019.3",
"unity": "2018.4",

2020-09-25 12:26 UTC, PavelKlym commented on com.stansassets.scene-management/BuildConfigurator/Editor/Extensions/PlatformsConfigurationExtension.cs
> +    public static class PlatformsConfigurationExtension
fixed

2020-09-25 12:27 UTC, PavelKlym commented on com.stansassets.scene-management/BuildConfigurator/Editor/Extensions/BuildConfigurationExtension.cs
> +    public static class BuildConfigurationExtension
fixed

2020-09-25 12:27 UTC, PavelKlym commented on com.stansassets.scene-management/Runtime/Statis/AdditiveScenesLoader.cs
> +#if UNITY_EDITOR
fixed

2020-09-25 12:27 UTC, PavelKlym commented on com.stansassets.scene-management/BuildConfigurator/Runtime/BuildConfiguration.cs
> +        public void InitializeBuildData(BuildTargetRuntime builtTarget)
fixed

2020-09-25 13:35 UTC, merged